modLoader="lowcodefml"
loaderVersion="[0,)"
issueTrackerURL="https://github.com/QikaHome/Ancient-Debris-Tweak/issues"
license="MIT"
[[mods]]
    modId="ancient-debris-tweak"
    version="0.1.0"
    displayName="Ancient Debris Tweak"
    description='''
    Some tweaks for ancient debris.
    '''
    logoFile="pack.png"

[[dependencies.ancient-debris-tweak]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
